# -*- coding: utf-8 -*-
"""taskLAB1orange.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K9MNDEM-MOIA-5RFFNtuVVQo0FinXBSc
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df=pd.read_csv('/content/HR_Dataset.csv')
df.head()

df.shape

df.columns

df.dtypes

df.describe()

df.duplicated().sum()

df['StartDate'] = pd.to_datetime(df['StartDate'], format='%d-%b-%y', errors='coerce')
df['ExitDate'] = pd.to_datetime(df['ExitDate'], format='%d-%b-%y', errors='coerce')
df['DOB'] = pd.to_datetime(df['DOB'], format='%d-%m-%Y', errors='coerce')
df['Survey Date'] = pd.to_datetime(df['Survey Date'], format='%d-%b-%y', errors='coerce')
df['Training Date'] = pd.to_datetime(df['Training Date'], format='%d-%b-%y', errors='coerce')
df.isna().sum()

len(df) #Survey Date has 3150 so its likely to be empty so we gotta drop it

(df.isna().sum() / len(df) * 100).sort_values(ascending=False)

df.drop(columns=['Survey Date'], inplace=True)

df.isna().sum()

(df.duplicated().sum() / len(df)) * 100

df.duplicated().sum()

df.duplicated().sum()

df = df.drop_duplicates()

df.duplicated().sum()

df.to_csv("cleaned_data_HR.csv", index=False)

data = pd.read_csv('/content/cleaned_data_HR.csv')
data.head()

data.dtypes

data['StartDate'] = pd.to_datetime(data['StartDate'])
data['ExitDate'] = pd.to_datetime(data['ExitDate'])
data['DOB'] = pd.to_datetime(data['DOB'])
data['Training Date'] = pd.to_datetime(data['Training Date'])

data.dtypes

df['BusinessUnit'].unique()

df['BusinessUnit'].value_counts()

df['EmployeeStatus'].value_counts()

df['Current Employee Rating'].mean()

df['Current Employee Rating'].max()

df['Engagement Score'].mean()

df['Training Cost'].describe()

df.groupby('DepartmentType')['Current Employee Rating'].mean()

df.groupby('BusinessUnit')['Satisfaction Score'].mean()

df.groupby('Training Program Name')['Training Cost'].mean()

df.groupby('GenderCode')['Work-Life Balance Score'].mean()

import matplotlib.pyplot as plt

# 1. Prepare the data by counting the occurrences of each department
data_counts = df["DepartmentType"].value_counts()

# 2. Set up a square figure size (1:1 ratio works best for circular charts)
plt.figure(figsize=(8, 8))

# 3. Create the donut chart
plt.pie(
    data_counts,
    labels=data_counts.index,
    autopct="%1.1f%%",  # Displays percentages inside the wedges
    startangle=140,  # Rotates the start for a cleaner look
    pctdistance=0.85,  # Places percentages nicely inside the donut ring
    wedgeprops={
        "width": 0.3,
        "edgecolor": "w",
    },  # 'width' creates the hole; 'edgecolor' adds white separation
)

# 4. Add a title and display
plt.title("Department Type Distribution", fontsize=14, pad=20)
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(data=df, x='DepartmentType')
plt.xticks(rotation=45)
plt.show()

sns.histplot(data=df, x='Current Employee Rating', bins=5, kde=True)
plt.title('Current Employee Rating Distribution')
plt.xlabel('Current Employee Rating')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Set a clean, modern visual theme
sns.set_theme(style="whitegrid")

# 2. Define the figure size
plt.figure(figsize=(9, 5.5))

# 3. Create the enhanced histogram
ax = sns.histplot(
    data=df,
    x="Current Employee Rating",
    bins=5,
    kde=True,
    color="#2b5c8f",  # A professional, deep slate blue for bars
    edgecolor="white",  # Adds a crisp boundary between bars
    linewidth=1.5,
    alpha=0.8,  # Slight transparency for a lighter feel
    line_kws={"color": "#de425b", "linewidth": 2.5},  # Contrasting coral color for the KDE line
)

# 4. Polish typography and spacing
plt.title(
    "Current Employee Rating Distribution",
    fontsize=16,
    fontweight="bold",
    pad=20,
    color="#2c3e50",
)
plt.xlabel("Current Employee Rating", fontsize=12, labelpad=10, fontweight="semibold")
plt.ylabel("Frequency", fontsize=12, labelpad=10, fontweight="semibold")

# 5. Remove unnecessary border lines ("chart junk")
sns.despine(left=True, bottom=True)

# 6. Ensure everything fits beautifully without clipping
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Set a clean, professional theme
sns.set_theme(style="whitegrid")

# 2. Set figure size (a slightly taller ratio works beautifully for horizontal plots)
plt.figure(figsize=(11, 6))

# 3. Create a horizontal boxplot
sns.boxplot(
    data=df,
    x="Training Cost",  # Flipped to X
    y="Training Program Name",  # Flipped to Y
    hue="Training Program Name", # Assign y variable to hue
    palette="mako",  # A sleek, modern color palette
    linewidth=1.5,  # Crisper box borders
    fliersize=4,  # Makes outlier dots slightly smaller and cleaner
    flierprops={
        "markerfacecolor": "#e74c3c",
        "markeredgecolor": "none",
        "alpha": 0.6,
    },
    legend=False # Set legend to False as recommended by the warning
)

# 4. Polish typography and add context
plt.title(
    "Training Cost Distribution by Program",
    fontsize=16,
    fontweight="bold",
    pad=20,
    color="#2c3e50",
)
plt.xlabel("Training Cost ($)", fontsize=12, labelpad=10, fontweight="semibold")
plt.ylabel("Training Program Name", fontsize=12, labelpad=10, fontweight="semibold")

# 5. Remove unnecessary border lines
sns.despine(left=True, bottom=True)

# 6. Ensure everything fits perfectly
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Set a clean, professional theme
sns.set_theme(style="whitegrid")

# 2. Set figure size (giving it a bit more vertical breathing room)
plt.figure(figsize=(11, 7))

# 3. Create a horizontal grouped countplot
ax = sns.countplot(
    data=df,
    y="BusinessUnit",  # Flipped to Y for clean text alignment
    hue="EmployeeStatus",
    palette="ch:start=.2,rot=-.3,dark=.4",  # A sophisticated, cohesive color palette
    edgecolor="white",
    linewidth=1,
)

# 4. Add exact counts onto the bars automatically
for container in ax.containers:
    ax.bar_label(container, fmt="%d", padding=6, fontsize=10, color="#4a4a4a")

# 5. Polish typography and labels
plt.title(
    "Employee Status Distribution by Business Unit",
    fontsize=16,
    fontweight="bold",
    pad=22,
    color="#2c3e50",
)
plt.xlabel("Employee Count", fontsize=12, labelpad=10, fontweight="semibold")
plt.ylabel("Business Unit", fontsize=12, labelpad=10, fontweight="semibold")

# 6. Clean up and reposition the legend
plt.legend(
    title="Employee Status",
    title_fontsize="11",
    loc="lower right",
    frameon=True,
    facecolor="white",
    edgecolor="#e0e0e0",
)

# 7. Remove unnecessary border lines
sns.despine(left=True, bottom=True)

# 8. Render beautifully
plt.tight_layout()
plt.show()

df['BusinessUnit'].value_counts().idxmax()

df.groupby('DepartmentType')['Current Employee Rating'].mean().sort_values(ascending=False)

df['Engagement Score'].corr(df['Satisfaction Score'])

df['Training Duration(Days)'].corr(df['Current Employee Rating'])

df.loc[df['Training Cost'].idxmax()]